
# Setup
title:            Roy Prigat
email:            royprigat@gmail.com
description:      'Personal Website'
url:              https://royprigat.github.io
baseurl:          /

author:          'Roy Prigat'

github_username:  royprigat
github:
  repo:           https://github.com/royprigat/royprigat.github.io

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-paginate
